services:
  nlp-notebook:
    image: b08x/notebook-nlp:latest
    container_name: notebook-nlp
    build:
      context: .
      dockerfile: nlp/Dockerfile
    volumes:
      # - $HOME/Documents:/home/jovyan/Library:ro
      - ${WORKSPACE:-./data}:/home/jovyan/work
    user: ${UID}:${GID}
    env_file:
      - .env
    environment:
      PUID: ${UID}
      PGID: ${GID}
      REDIS_URL: "redis://redis:6379/0"
      OHM_URL: "redis://redis:6379/1"
    ports:
      - 8888:8888
    networks:
      - jupyter   
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
      - "8081:8081"
      - "8001:8001"
    networks:
      - jupyter
  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: rubynlp
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgvector_local_data:/data
      - pgvector_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 3s
      timeout: 10s
      retries: 20      
    networks:
      - jupyter

volumes:
  pgvector_local_data:
    driver: local
  pgvector_pgdata:
    driver: local
  redis_data:
    driver: local

networks:
  jupyter:
    driver: bridge
