name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "binder/*"
      - "docs/*"
  pull_request:
    paths-ignore:
      - "README.md"
      - "binder/*"
      - "docs/*"

jobs:
  build_and_push_base:
    name: notebook-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: "3.2"

      - name: Build base image
        run: rake build/base

      - name: Tag base image
        run: |
          tag=${GITHUB_SHA:0:12}
          docker tag b08x/notebook-base:latest b08x/notebook-base:${tag}

      - name: List images
        run: docker images --format '{{.Repository}}:{{.Tag}}\t{{.ID}}'

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push base image to DockerHub
        if: github.ref == 'refs/heads/main'
        run: |
          docker images --format '{{.Repository}}:{{.Tag}}' | grep b08x/notebook-base | while read image_name; do
            echo "Pushing ${image_name}"
            docker push ${image_name}
          done

  build_and_push_nlp:
    name: notebook-nlp
    runs-on: ubuntu-latest
    needs: build_and_push_base # Ensures this job runs only after build_and_push_base succeeds
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: "3.2"

      - name: Build nlp image
        run: rake build/nlp

      - name: Tag nlp image
        run: |
          tag=${GITHUB_SHA:0:12}
          docker tag b08x/notebook-nlp:latest b08x/notebook-nlp:${tag}

      - name: List images
        run: docker images --format '{{.Repository}}:{{.Tag}}\t{{.ID}}'

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push nlp image to DockerHub
        if: github.ref == 'refs/heads/main'
        run: |
          docker images --format '{{.Repository}}:{{.Tag}}' | grep b08x/notebook-nlp | while read image_name; do
            echo "Pushing ${image_name}"
            docker push ${image_name}
          done
