name: CI

on:
  push:
    branches: ["development"]
    paths-ignore:
      - "README.md"
      - "binder/*"
      - "docs/*"
  pull_request:
    paths-ignore:
      - "README.md"
      - "binder/*"
      - "docs/*"

jobs:
  build_and_push:
    strategy:
      matrix:
        image_base_name:
          # - full
          # - minimal
          # - datascience
          # - llamaindex
          - nlp
          # - audio

    name: notebook-${{ matrix.image_base_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: "3.1"

      - name: Build images
        run: rake build/${{ matrix.image_base_name }}

      - name: Tag
        run: |
          tag=${GITHUB_SHA:0:12}
          docker tag b08x/notebook-${{ matrix.image_base_name }}:latest b08x/notebook-${{ matrix.image_base_name }}:${tag}

      - name: List images
        run: docker images --format '{{.Repository}}:{{.Tag}}\t{{.ID}}'

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/development'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push images to DockerHub
        if: github.ref == 'refs/heads/development'
        run: |
          docker images --format '{{.Repository}}:{{.Tag}}' | grep b08x/notebook-${{ matrix.image_base_name }} | while read image_name; do
            echo "Pushing ${image_name}"
            docker push ${image_name}
          done
